name: Compile Latex

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    runs-on: ubuntu-latest
    name: A job to compile Latex
    steps:
      - uses: actions/checkout@v1
      - name: Compile LateX
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: shreeram_modi.tex
          push: yes # optional, default is no
